<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-06-29T13:16:00 IST" name="Default suite" finished-at="2022-06-29T13:16:43 IST" duration-ms="42233">
    <groups>
    </groups>
    <test started-at="2022-06-29T13:16:00 IST" name="Default test" finished-at="2022-06-29T13:16:43 IST" duration-ms="42233">
      <class name="com.auto.testcases.LoginTest">
        <test-method is-config="true" signature="setData()[pri:0, instance:com.auto.testcases.LoginTest@bd4dc25]" started-at="2022-06-29T13:15:59 IST" name="setData" finished-at="2022-06-29T13:16:00 IST" duration-ms="1475" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setData -->
        <test-method is-config="true" signature="Start()[pri:0, instance:com.auto.testcases.LoginTest@bd4dc25]" started-at="2022-06-29T13:16:00 IST" name="Start" finished-at="2022-06-29T13:16:08 IST" duration-ms="8118" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Start -->
        <test-method signature="LoginTestMethod()[pri:0, instance:com.auto.testcases.LoginTest@bd4dc25]" started-at="2022-06-29T13:16:09 IST" name="LoginTestMethod" finished-at="2022-06-29T13:16:42 IST" duration-ms="33370" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:829)
at com.auto.testcases.LoginTest.LoginTestMethod(LoginTest.java:25)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTestMethod -->
        <test-method is-config="true" signature="tearDownMethod(org.testng.ITestResult)[pri:0, instance:com.auto.testcases.LoginTest@bd4dc25]" started-at="2022-06-29T13:16:42 IST" name="tearDownMethod" finished-at="2022-06-29T13:16:42 IST" duration-ms="328" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=LoginTestMethod status=FAILURE method=LoginTest.LoginTestMethod()[pri:0, instance:com.auto.testcases.LoginTest@bd4dc25] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownMethod -->
        <test-method is-config="true" signature="closeAppMethod()[pri:0, instance:com.auto.testcases.LoginTest@bd4dc25]" started-at="2022-06-29T13:16:42 IST" name="closeAppMethod" finished-at="2022-06-29T13:16:43 IST" duration-ms="296" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeAppMethod -->
      </class> <!-- com.auto.testcases.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
